# Site settings
title: Bitbetter
header-img: img/home-bg-01.jpg
email: hello@bitbetter.se
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://bitbetter.se"
twitter_username: bitbetter
github_username: bitbetter
facebook_username: bitbetter

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
